### ISSUE TITLE
master is broken

### ISSUE THREAD

**Issue by G3z** [arboleya/fs-util#2]
but dev seems to be working,
until you fix this polvo will crash on each file change (with -w option enabled)

running tests in master returns 5 errors

``` bash
g3z@JBook ~/Documents/Node.js/fs-util $ make test
rm -rf tests/tmp-* tests/a
node_modules/coffee-script/bin/coffee -j lib/fs-util.js -c src/*.coffee
node_modules/mocha/bin/mocha tests/* \
        --compilers coffee:coffee-script \
        --require should --reporter spec

Current version is: 0.3.10


  • FS Tools
    When making a deep-dir structure
      ✓ the structure must to be created
    When touching a file
      ✓ the file must be touched
    When copying a structure
      ✓ the structure must to be copied
    When copying a single file
      ✓ the file must to be copied
    When searching a file
      ✓ the search must to return the proper results
    When searching a directory
      ✓ the search must to return the proper results
    When listing a directory
      ✓ the list must to return the dir contents
    When removing a strucuture recursively
      ✓ the structure must to removed recursively

  • FS Watcher
    When watching a directory tree
      ✓ the `watch` event should be emitted properly
    When creating a dir inside that tree
      ✓ the `watch` and `create` event should be emitted properly (163ms)
    When deleting this dir
      ✓ the `unwatch` and `delete` events should be emitted properly (150ms)
    When creating a file inside the watched dir
      1) the `created` and `watch` events should be emitted properly
    When updating this file (a little delay needed here, pay no mind)
      2) the `change` event should be emitted properly
    When deleting this file
      3) the `unwatch` and `delete` events should be emitted properly
    When moving an existent structure inside the watched tree
      4) the `create` and `watch` events should be emitted properly for all files and dirs
    When deleting this structure
      5) the `delete` and `unwatch` events should be emitted properly for all files and dirs


  ✖ 5 of 16 tests failed:

  1) • FS Watcher When creating a file inside the watched dir the `created` and `watch` events should be emitted properly:
     TypeError: Cannot call method 'test' of undefined
      at DirWatcher.diff (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:346:45)
      at DirWatcher.onchange (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:312:17)
      at FSWatcher.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:4:61)
      at FSWatcher.EventEmitter.emit (events.js:98:17)
      at FSEvent.FSWatcher._handle.onchange (fs.js:1039:12)

  2) • FS Watcher When updating this file (a little delay needed here, pay no mind) the `change` event should be emitted properly:
     TypeError: Cannot call method 'test' of undefined
      at DirWatcher.diff (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:346:45)
      at DirWatcher.onchange (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:312:17)
      at FSWatcher.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:4:61)
      at FSWatcher.EventEmitter.emit (events.js:98:17)
      at FSEvent.FSWatcher._handle.onchange (fs.js:1039:12)

  3) • FS Watcher When deleting this file the `unwatch` and `delete` events should be emitted properly:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  4) • FS Watcher When moving an existent structure inside the watched tree the `create` and `watch` events should be emitted properly for all files and dirs:

      actual expected

      /Users/g3z/Documents/Node.js/fs-util/tests/tmp-watcher/filea/b/c/d/e/cinco.coffee

   expected '/Users/g3z/Documents/Node.js/fs-util/tests/tmp-watcher/a/b/c/d/e/cinco.coffee' to equal '/Users/g3z/Documents/Node.js/fs-util/tests/tmp-watcher/file.coffee'
      at Object.Assertion.equal (/Users/g3z/Documents/Node.js/fs-util/node_modules/should/lib/should.js:303:10)
      at Watcher.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/tests/fs-watcher.coffee:105:36)
      at Watcher.g (events.js:175:14)
      at Watcher.EventEmitter.emit (events.js:117:20)
      at FileWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:181:29)
      at new FileWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:170:12)
      at DirWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:260:22)
      at new DirWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:235:12)
      at DirWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:253:17)
      at new DirWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:235:12)
      at DirWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:253:17)
      at new DirWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:235:12)
      at DirWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:253:17)
      at new DirWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:235:12)
      at DirWatcher.init (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:253:17)
      at new DirWatcher (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:235:12)
      at DirWatcher.onchange (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:323:46)
      at FSWatcher.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/lib/fs-util.js:4:61)
      at FSWatcher.EventEmitter.emit (events.js:98:17)
      at FSEvent.FSWatcher._handle.onchange (fs.js:1039:12)

  5) • FS Watcher When deleting this structure the `delete` and `unwatch` events should be emitted properly for all files and dirs:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/g3z/Documents/Node.js/fs-util/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)


make: *** [test] Error 5
```

**Comment by arboleya** [comment]
In the heat of moment I have improved the dev version and published the master one! Dumb mistake.

Thanks for reporting, I'm on it.

**Comment by arboleya** [comment]
Ooops, that was not case. Actually, it was inverse. The dev is out of date, that's why it's working.

Anyway, I'm gonna fix it.
