### ISSUE TITLE
"TypeError: Cannot read property 'mtime' of null"

### ISSUE THREAD

**Issue by hems** [arboleya/fs-util#5]
Using it for some time watching an assets folder, then after adding / deleting loads of files i got this error and the process exited.

could this code be wrapped into a try / catch and then outputted to stdout instead of becoming a fatal ?

/var/projects/watcher/node_modules/fs-util/lib/fs-util.js:210
      if (this.curr.mtime > this.prev.mtime) {
                                     ^
TypeError: Cannot read property 'mtime' of null
    at FileWatcher.onchange (/var/projects/watcher/node_modules/fs-util/lib/fs-util.js:210:38)
    at StatWatcher.<anonymous> (/var/projects/watcher/node_modules/fs-util/lib/fs-util.js:4:61)
    at StatWatcher.EventEmitter.emit (events.js:98:17)
    at StatWatcher._handle.onchange (fs.js:1109:10)
make: **\* [watch.ark] Error 8

**Comment by arboleya** [comment]
Are you able to reproduce it easily? If yes, with one specific project or with many?

In case it's easily reproducible, is it possible to build a test case for it?

**Comment by hems** [comment]
sorry i should have took the time, i didn't. now i don't really have it happening.

anyway seems like a trivial problem? 

this.curr is null at some point but somehow the event was triggered, seems like some "late event" happening.

also somehow we might benefit from having a "global try catch", so errors like that wouldn't stop the service?

**Comment by arboleya** [comment]
I guess the better is to find what exactly is the error about, and try to handle it specifically. Hide it is easy, but not much efficient
